% Modelling and control of a Magnetic Levitation System
%
% This project explores traditional and modern control theory techniques
% to stabilize the position of a ferromagnetic ball suspended in a magnetic
% field generated by two electromagnets.
% A "Model-based design" (MBD) approach has been adopted.
%
% Author: Tommaso Bocchietti, Daniele Cianca, Sara Orazzo
% Date: 00/00/2024
%
% Requires:
%   - Simulink
%   - Coder Toolbox
%   - INTECO MSL2EM Toolbox (licensed from the producer)
%
% Reference course: 062020 (Politecnico di Milano A.Y. 2024/2025)

clc
clear variables
close all

%% Controller labels

controller_labels = [
    "PID classical"
    "PID anti-windup"
    "PID cascade"
    "PID gain scheduling"
    "LQR classical"
    "LQR tracking"
    "LQI classical"
    "LQG classical"
    % "MCP"
    ]';


%% Simulation launcher

model = Simulink.SimulationInput("System");
model = model.setModelParameter("SimulationMode", "normal");
model = model.setModelParameter("SolverType", "Variable-step");
model = model.setModelParameter("StopTime", "4");
% slbuild(model)

for controller_label = controller_labels
    
    model_with_controller = model.setBlockParameter("System/Controller (K)", "LabelModeActiveChoice", controller_label);

    out = sim([
        model_with_controller.setBlockParameter("System/Plant (G)", "LabelModeActiveChoice", "Literature model");
        model_with_controller.setBlockParameter("System/Plant (G)", "LabelModeActiveChoice", "Lagrangian model");
        ]);

    % out.ErrorMessage

    try %#ok<TRYNC>
        movefile("runs\_simout_1.mat", strcat("runs\step\literature_", replace(controller_label, ' ', '_'), ".mat"))
        movefile("runs\_simout_2.mat", strcat("runs\step\lagrangian_", replace(controller_label, ' ', '_'), ".mat"))
    end

end